---
title: "Exercise 3: Paramteric regression models and model checking"
output: pdf_document
---

# Weibull distribution
1. How is the empirical check for the Weibull distribution performed in terms of its survival function?

(- check log-log-plot for Kaplan-Mayer estimator)


2. Use the result of (1) for checking the Weibull assumption for the failure time in Veteran data (Use Kaplan-Meier estimate obtained in Exercise 1).


3. Further (a) repeat the Weibull assumpation check separately for the treatment groups. Interpret. (b)
Also, check the hypothesis whether the data from the treatment groups can be assumed to be drawn
from the same Weibull distribution or not, [use likelihood ratio test]. Interpret.


4. Show that the Weibull distribution can be expressed as Y = α + σW where Y = log T, α = − log λ and σ = γ−1 and T has Weibull distribution with survival function S(t) = exp[−(λt)γ].


5. Perform log-rank test to compare (a) treatments, (2) prior treatment, and (3) cell types.



# Fitting exponential and Weibull regression models to Veteran data
Load veteran data from library(survival).
1. Analyse the data with an exponential regression model using treatment status, performance status,
prior therapy status and cell type as the explanatory variables.

2. Repeat the above analysis using Weibull model. [Use the weibreg() function].


3. Interpret the results for the regression parameters. Which category of cell type is used as a reference
category?
